config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kele</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink="true" >
  <div class="container">
    <ul class="nav nav-tabs">
     <li><%= link_to "Home", welcome_index_path %></li>
     <li><%= link_to "About", welcome_about_path %></li>

<%= yield %>

  </div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>About Kele</h1>
<p>Kele is a Ruby Gem API client to access the Bloc API.
</br>
<p>Bloc's API provides an external facing JSON Web Token authorized gateway to the Bloc application.</p>
<ul>
  <li>Kele API Client will provide easy access to and use of the student endpoints of Bloc's API.</p></li>
</ul>
<p>Created by Sylvia :)</p>

app/views/welcome/index.html.erb
<h1>Welcome to Kele</h1>
<p>This is the home page for Kele.</p>